### ISSUE TITLE
Redesign [T] and [D]

### ISSUE THREAD

**Issue by Branchverse** [dopeshot/nextparty.io-frontend#57]
[T] and [D] is not understood, maybe replace it with [?] and [!]

**Comment by LarsFlieger** [comment]
True good point! Maybe we find a symbol or some other "icon" to show truth / dare.

**Comment by LarsFlieger** [comment]
![image](https://user-images.githubusercontent.com/47084064/174166971-efe6e08a-5f38-414e-af2e-c4b2f0296009.png)
Now looks like this :)
